# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Hugrid - Grid Theme For Hugo"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "BG Insights - Data Visualization Studio"
    subtitle = "<blockquote>“Torture the data, and it will confess to anything” - Ronald Coase</blockquote>"
    subtitle2 = "BG Insights is a Data Studio helping businesses in their entire data process from data collection to visualization in order share its own story."
    author = "Bamby Gassama"
    description = "Hugrid - grid theme for Hugo with an expanding image preview."
    keywords = "Hugo, Hugo theme, grid theme, portfolio, bookmarks, collection, contacts"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "FIND OUT MORE"

    # Footer text
    footertext = "© 2018 | Website designed by BG Insights"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']

[params.font]
    # Some example fonts: Domine, Raleway, "Gentium Basic", Lato
      body = "Lato"
      heading = "Pacifico"
      blockquote = "Gentium Basic"
      nav = "Domine"
      paragraph = "Roboto"
